export interface FigletFont {
  name: string;
  ext: 'flf' | 'tlf';
}

export const FIGLET_FONTS: FigletFont[] = [
  { name: "1Row", ext: "flf" },
  { name: "3-D", ext: "flf" },
  { name: "3D Diagonal", ext: "flf" },
  { name: "3D-ASCII", ext: "flf" },
  { name: "3d", ext: "flf" },
  { name: "3d_diagonal", ext: "flf" },
  { name: "3x5", ext: "flf" },
  { name: "4Max", ext: "flf" },
  { name: "5 Line Oblique", ext: "flf" },
  { name: "5lineoblique", ext: "flf" },
  { name: "AMC 3 Line", ext: "flf" },
  { name: "AMC 3 Liv1", ext: "flf" },
  { name: "AMC AAA01", ext: "flf" },
  { name: "AMC Neko", ext: "flf" },
  { name: "AMC Razor", ext: "flf" },
  { name: "AMC Razor2", ext: "flf" },
  { name: "AMC Slash", ext: "flf" },
  { name: "AMC Slider", ext: "flf" },
  { name: "AMC Thin", ext: "flf" },
  { name: "AMC Tubes", ext: "flf" },
  { name: "AMC Untitled", ext: "flf" },
  { name: "ANSI Regular", ext: "flf" },
  { name: "ANSI Shadow", ext: "flf" },
  { name: "ASCII New Roman", ext: "flf" },
  { name: "Acrobatic", ext: "flf" },
  { name: "Alligator", ext: "flf" },
  { name: "Alligator2", ext: "flf" },
  { name: "Alpha", ext: "flf" },
  { name: "Alphabet", ext: "flf" },
  { name: "Arrows", ext: "flf" },
  { name: "Avatar", ext: "flf" },
  { name: "B1FF", ext: "flf" },
  { name: "Banner", ext: "flf" },
  { name: "Banner3-D", ext: "flf" },
  { name: "Banner3", ext: "flf" },
  { name: "Banner4", ext: "flf" },
  { name: "Barbwire", ext: "flf" },
  { name: "Basic", ext: "flf" },
  { name: "Bear", ext: "flf" },
  { name: "Bell", ext: "flf" },
  { name: "Benjamin", ext: "flf" },
  { name: "Big Chief", ext: "flf" },
  { name: "Big Money-ne", ext: "flf" },
  { name: "Big Money-nw", ext: "flf" },
  { name: "Big Money-se", ext: "flf" },
  { name: "Big Money-sw", ext: "flf" },
  { name: "Big", ext: "flf" },
  { name: "Bigfig", ext: "flf" },
  { name: "Binary", ext: "flf" },
  { name: "Block", ext: "flf" },
  { name: "Blocks", ext: "flf" },
  { name: "Bloody", ext: "flf" },
  { name: "Bolger", ext: "flf" },
  { name: "Braced", ext: "flf" },
  { name: "Bright", ext: "flf" },
  { name: "Broadway KB", ext: "flf" },
  { name: "Broadway", ext: "flf" },
  { name: "Bubble", ext: "flf" },
  { name: "Bulbhead", ext: "flf" },
  { name: "Caligraphy", ext: "flf" },
  { name: "Caligraphy2", ext: "flf" },
  { name: "Calvin S", ext: "flf" },
  { name: "Cards", ext: "flf" },
  { name: "Catwalk", ext: "flf" },
  { name: "Chiseled", ext: "flf" },
  { name: "Chunky", ext: "flf" },
  { name: "Coinstak", ext: "flf" },
  { name: "Cola", ext: "flf" },
  { name: "Colossal", ext: "flf" },
  { name: "Computer", ext: "flf" },
  { name: "Contessa", ext: "flf" },
  { name: "Contrast", ext: "flf" },
  { name: "Cosmike", ext: "flf" },
  { name: "Crawford", ext: "flf" },
  { name: "Crawford2", ext: "flf" },
  { name: "Crazy", ext: "flf" },
  { name: "Cricket", ext: "flf" },
  { name: "Cursive", ext: "flf" },
  { name: "Cyberlarge", ext: "flf" },
  { name: "Cybermedium", ext: "flf" },
  { name: "Cybersmall", ext: "flf" },
  { name: "Cygnet", ext: "flf" },
  { name: "DANC4", ext: "flf" },
  { name: "DOS Rebel", ext: "flf" },
  { name: "DWhistled", ext: "flf" },
  { name: "Dancing Font", ext: "flf" },
  { name: "Decimal", ext: "flf" },
  { name: "Def Leppard", ext: "flf" },
  { name: "Delta Corps Priest 1", ext: "flf" },
  { name: "Diamond", ext: "flf" },
  { name: "Diet Cola", ext: "flf" },
  { name: "Digital", ext: "flf" },
  { name: "Doh", ext: "flf" },
  { name: "Doom", ext: "flf" },
  { name: "Dot Matrix", ext: "flf" },
  { name: "Double Shorts", ext: "flf" },
  { name: "Double", ext: "flf" },
  { name: "Dr Pepper", ext: "flf" },
  { name: "Efti Chess", ext: "flf" },
  { name: "Efti Font", ext: "flf" },
  { name: "Efti Italic", ext: "flf" },
  { name: "Efti Piti", ext: "flf" },
  { name: "Efti Robot", ext: "flf" },
  { name: "Efti Wall", ext: "flf" },
  { name: "Efti Water", ext: "flf" },
  { name: "Electronic", ext: "flf" },
  { name: "Elite", ext: "flf" },
  { name: "Epic", ext: "flf" },
  { name: "Fender", ext: "flf" },
  { name: "Filter", ext: "flf" },
  { name: "Fire Font-k", ext: "flf" },
  { name: "Fire Font-s", ext: "flf" },
  { name: "Flipped", ext: "flf" },
  { name: "Flower Power", ext: "flf" },
  { name: "Four Tops", ext: "flf" },
  { name: "Fraktur", ext: "flf" },
  { name: "Fun Face", ext: "flf" },
  { name: "Fun Faces", ext: "flf" },
  { name: "Fuzzy", ext: "flf" },
  { name: "Georgi16", ext: "flf" },
  { name: "Georgia11", ext: "flf" },
  { name: "Ghost", ext: "flf" },
  { name: "Ghoulish", ext: "flf" },
  { name: "Glenyn", ext: "flf" },
  { name: "Goofy", ext: "flf" },
  { name: "Gothic", ext: "flf" },
  { name: "Graceful", ext: "flf" },
  { name: "Gradient", ext: "flf" },
  { name: "Graffiti", ext: "flf" },
  { name: "Greek", ext: "flf" },
  { name: "Heart Left", ext: "flf" },
  { name: "Heart Right", ext: "flf" },
  { name: "Henry 3D", ext: "flf" },
  { name: "Hex", ext: "flf" },
  { name: "Hieroglyphs", ext: "flf" },
  { name: "Hollywood", ext: "flf" },
  { name: "Horizontal Left", ext: "flf" },
  { name: "Horizontal Right", ext: "flf" },
  { name: "ICL-1900", ext: "flf" },
  { name: "Impossible", ext: "flf" },
  { name: "Invita", ext: "flf" },
  { name: "Isometric1", ext: "flf" },
  { name: "Isometric2", ext: "flf" },
  { name: "Isometric3", ext: "flf" },
  { name: "Isometric4", ext: "flf" },
  { name: "Italic", ext: "flf" },
  { name: "Ivrit", ext: "flf" },
  { name: "JS Block Letters", ext: "flf" },
  { name: "JS Bracket Letters", ext: "flf" },
  { name: "JS Capital Curves", ext: "flf" },
  { name: "JS Cursive", ext: "flf" },
  { name: "JS Stick Letters", ext: "flf" },
  { name: "Jacky", ext: "flf" },
  { name: "Jazmine", ext: "flf" },
  { name: "Jerusalem", ext: "flf" },
  { name: "Katakana", ext: "flf" },
  { name: "Kban", ext: "flf" },
  { name: "Keyboard", ext: "flf" },
  { name: "Knob", ext: "flf" },
  { name: "Konto Slant", ext: "flf" },
  { name: "Konto", ext: "flf" },
  { name: "LCD", ext: "flf" },
  { name: "Larry 3D 2", ext: "flf" },
  { name: "Larry 3D", ext: "flf" },
  { name: "Lean", ext: "flf" },
  { name: "Letters", ext: "flf" },
  { name: "Lil Devil", ext: "flf" },
  { name: "Line Blocks", ext: "flf" },
  { name: "Linux", ext: "flf" },
  { name: "Lockergnome", ext: "flf" },
  { name: "Madrid", ext: "flf" },
  { name: "Marquee", ext: "flf" },
  { name: "Maxfour", ext: "flf" },
  { name: "Merlin1", ext: "flf" },
  { name: "Merlin2", ext: "flf" },
  { name: "Mike", ext: "flf" },
  { name: "Mini", ext: "flf" },
  { name: "Mirror", ext: "flf" },
  { name: "Mnemonic", ext: "flf" },
  { name: "Modular", ext: "flf" },
  { name: "Morse", ext: "flf" },
  { name: "Morse2", ext: "flf" },
  { name: "Moscow", ext: "flf" },
  { name: "Mshebrew210", ext: "flf" },
  { name: "Muzzle", ext: "flf" },
  { name: "NScript", ext: "flf" },
  { name: "NT Greek", ext: "flf" },
  { name: "NV Script", ext: "flf" },
  { name: "Nancyj-Fancy", ext: "flf" },
  { name: "Nancyj-Improved", ext: "flf" },
  { name: "Nancyj-Underlined", ext: "flf" },
  { name: "Nancyj", ext: "flf" },
  { name: "Nipples", ext: "flf" },
  { name: "O8", ext: "flf" },
  { name: "OS2", ext: "flf" },
  { name: "Octal", ext: "flf" },
  { name: "Ogre", ext: "flf" },
  { name: "Old Banner", ext: "flf" },
  { name: "Patorjk's Cheese", ext: "flf" },
  { name: "Patorjk-HeX", ext: "flf" },
  { name: "Pawp", ext: "flf" },
  { name: "Peaks Slant", ext: "flf" },
  { name: "Peaks", ext: "flf" },
  { name: "Pebbles", ext: "flf" },
  { name: "Pepper", ext: "flf" },
  { name: "Poison", ext: "flf" },
  { name: "Puffy", ext: "flf" },
  { name: "Puzzle", ext: "flf" },
  { name: "Pyramid", ext: "flf" },
  { name: "Rammstein", ext: "flf" },
  { name: "Rectangles", ext: "flf" },
  { name: "Red Phoenix", ext: "flf" },
  { name: "Relief", ext: "flf" },
  { name: "Relief2", ext: "flf" },
  { name: "Reverse", ext: "flf" },
  { name: "Roman", ext: "flf" },
  { name: "Rot13", ext: "flf" },
  { name: "Rotated", ext: "flf" },
  { name: "Rounded", ext: "flf" },
  { name: "Rowan Cap", ext: "flf" },
  { name: "Rozzo", ext: "flf" },
  { name: "Runic", ext: "flf" },
  { name: "Runyc", ext: "flf" },
  { name: "S Blood", ext: "flf" },
  { name: "SL Script", ext: "flf" },
  { name: "Santa Clara", ext: "flf" },
  { name: "Script", ext: "flf" },
  { name: "Serifcap", ext: "flf" },
  { name: "Shadow", ext: "flf" },
  { name: "Shimrod", ext: "flf" },
  { name: "Short", ext: "flf" },
  { name: "Slant Relief", ext: "flf" },
  { name: "Slant", ext: "flf" },
  { name: "Slide", ext: "flf" },
  { name: "Small Caps", ext: "flf" },
  { name: "Small Isometric1", ext: "flf" },
  { name: "Small Keyboard", ext: "flf" },
  { name: "Small Poison", ext: "flf" },
  { name: "Small Script", ext: "flf" },
  { name: "Small Shadow", ext: "flf" },
  { name: "Small Slant", ext: "flf" },
  { name: "Small Tengwar", ext: "flf" },
  { name: "Small", ext: "flf" },
  { name: "Soft", ext: "flf" },
  { name: "Speed", ext: "flf" },
  { name: "Spliff", ext: "flf" },
  { name: "Stacey", ext: "flf" },
  { name: "Stampate", ext: "flf" },
  { name: "Stampatello", ext: "flf" },
  { name: "Standard", ext: "flf" },
  { name: "Star Strips", ext: "flf" },
  { name: "Star Wars", ext: "flf" },
  { name: "Stellar", ext: "flf" },
  { name: "Stforek", ext: "flf" },
  { name: "Stick Letters", ext: "flf" },
  { name: "Stop", ext: "flf" },
  { name: "Straight", ext: "flf" },
  { name: "Stronger Than All", ext: "flf" },
  { name: "Sub-Zero", ext: "flf" },
  { name: "Swamp Land", ext: "flf" },
  { name: "Swan", ext: "flf" },
  { name: "Sweet", ext: "flf" },
  { name: "THIS", ext: "flf" },
  { name: "Tanja", ext: "flf" },
  { name: "Tengwar", ext: "flf" },
  { name: "Term", ext: "flf" },
  { name: "Test1", ext: "flf" },
  { name: "The Edge", ext: "flf" },
  { name: "Thick", ext: "flf" },
  { name: "Thin", ext: "flf" },
  { name: "Thorned", ext: "flf" },
  { name: "Three Point", ext: "flf" },
  { name: "Ticks Slant", ext: "flf" },
  { name: "Ticks", ext: "flf" },
  { name: "Tiles", ext: "flf" },
  { name: "Tinker-Toy", ext: "flf" },
  { name: "Tombstone", ext: "flf" },
  { name: "Train", ext: "flf" },
  { name: "Trek", ext: "flf" },
  { name: "Tsalagi", ext: "flf" },
  { name: "Tubes-Regular", ext: "flf" },
  { name: "Tubes-Smushed", ext: "flf" },
  { name: "Tubular", ext: "flf" },
  { name: "Twisted", ext: "flf" },
  { name: "Two Point", ext: "flf" },
  { name: "USA Flag", ext: "flf" },
  { name: "Univers", ext: "flf" },
  { name: "Varsity", ext: "flf" },
  { name: "Wavy", ext: "flf" },
  { name: "Weird", ext: "flf" },
  { name: "Wet Letter", ext: "flf" },
  { name: "Whimsy", ext: "flf" },
  { name: "Wow", ext: "flf" },
  { name: "alligator3", ext: "flf" },
  { name: "amc3line", ext: "flf" },
  { name: "amc3liv1", ext: "flf" },
  { name: "amcaaa01", ext: "flf" },
  { name: "amcneko", ext: "flf" },
  { name: "amcrazo2", ext: "flf" },
  { name: "amcrazor", ext: "flf" },
  { name: "amcslash", ext: "flf" },
  { name: "amcslder", ext: "flf" },
  { name: "amcthin", ext: "flf" },
  { name: "amctubes", ext: "flf" },
  { name: "amcun1", ext: "flf" },
  { name: "ascii12", ext: "tlf" },
  { name: "ascii9", ext: "tlf" },
  { name: "ascii_new_roman", ext: "flf" },
  { name: "bigascii12", ext: "tlf" },
  { name: "bigascii9", ext: "tlf" },
  { name: "bigchief", ext: "flf" },
  { name: "bigmono12", ext: "tlf" },
  { name: "bigmono9", ext: "tlf" },
  { name: "broadway_kb", ext: "flf" },
  { name: "calgphy2", ext: "flf" },
  { name: "circle", ext: "tlf" },
  { name: "cosmic", ext: "flf" },
  { name: "dancingfont", ext: "flf" },
  { name: "defleppard", ext: "flf" },
  { name: "dietcola", ext: "flf" },
  { name: "dosrebel", ext: "flf" },
  { name: "dotmatrix", ext: "flf" },
  { name: "doubleshorts", ext: "flf" },
  { name: "drpepper", ext: "flf" },
  { name: "eftichess", ext: "flf" },
  { name: "eftifont", ext: "flf" },
  { name: "eftipiti", ext: "flf" },
  { name: "eftirobot", ext: "flf" },
  { name: "eftitalic", ext: "flf" },
  { name: "eftiwall", ext: "flf" },
  { name: "eftiwater", ext: "flf" },
  { name: "emboss", ext: "tlf" },
  { name: "emboss2", ext: "tlf" },
  { name: "fire_font-k", ext: "flf" },
  { name: "fire_font-s", ext: "flf" },
  { name: "flowerpower", ext: "flf" },
  { name: "fourtops", ext: "flf" },
  { name: "funface", ext: "flf" },
  { name: "funfaces", ext: "flf" },
  { name: "future", ext: "tlf" },
  { name: "halfiwi", ext: "flf" },
  { name: "heart_left", ext: "flf" },
  { name: "heart_right", ext: "flf" },
  { name: "henry3d", ext: "flf" },
  { name: "horizontalleft", ext: "flf" },
  { name: "horizontalright", ext: "flf" },
  { name: "koholint", ext: "flf" },
  { name: "kompaktblk", ext: "flf" },
  { name: "kontoslant", ext: "flf" },
  { name: "larry3d", ext: "flf" },
  { name: "letter", ext: "tlf" },
  { name: "lildevil", ext: "flf" },
  { name: "lineblocks", ext: "flf" },
  { name: "maxiwi", ext: "flf" },
  { name: "miniwi", ext: "flf" },
  { name: "mono12", ext: "tlf" },
  { name: "mono9", ext: "flf" },
  { name: "mono9", ext: "tlf" },
  { name: "ntgreek", ext: "flf" },
  { name: "oldbanner", ext: "flf" },
  { name: "pagga", ext: "tlf" },
  { name: "peaksslant", ext: "flf" },
  { name: "rebel", ext: "tlf" },
  { name: "red_phoenix", ext: "flf" },
  { name: "rev", ext: "flf" },
  { name: "rowancap", ext: "flf" },
  { name: "rusto", ext: "tlf" },
  { name: "rustofat", ext: "tlf" },
  { name: "s-relief", ext: "flf" },
  { name: "santaclara", ext: "flf" },
  { name: "sblood", ext: "flf" },
  { name: "six-fo", ext: "flf" },
  { name: "slscript", ext: "flf" },
  { name: "smallcaps", ext: "flf" },
  { name: "smascii12", ext: "tlf" },
  { name: "smascii9", ext: "tlf" },
  { name: "smblock", ext: "tlf" },
  { name: "smbraille", ext: "tlf" },
  { name: "smisome1", ext: "flf" },
  { name: "smkeyboard", ext: "flf" },
  { name: "smmono12", ext: "tlf" },
  { name: "smmono9", ext: "tlf" },
  { name: "smpoison", ext: "flf" },
  { name: "smscript", ext: "flf" },
  { name: "smshadow", ext: "flf" },
  { name: "smslant", ext: "flf" },
  { name: "smtengwar", ext: "flf" },
  { name: "starstrips", ext: "flf" },
  { name: "starwars", ext: "flf" },
  { name: "stencil", ext: "flf" },
  { name: "swampland", ext: "flf" },
  { name: "terminus", ext: "flf" },
  { name: "terminus_dots", ext: "flf" },
  { name: "threepoint", ext: "flf" },
  { name: "ticksslant", ext: "flf" },
  { name: "twopoint", ext: "flf" },
  { name: "ublk", ext: "flf" },
  { name: "usaflag", ext: "flf" },
  { name: "wetletter", ext: "flf" },
  { name: "wideterm", ext: "tlf" }
];
